name: Liquibase Checks with GitHub Actions Demo
on: 
  workflow_dispatch
jobs:
  liquibase-actions:
    name: Liquibase Actions
    runs-on: ubuntu-latest
    env: 
        LB_TAG: ${{ github.run_number }}
        LIQUIBASE_COMMAND_CHANGELOG_FILE: liquibase/changelogs/changelog-checks.sql
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{ secrets.LIQUIBASE_DEV_USER }}
          POSTGRES_PASSWORD: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}
          POSTGRES_DB: ${{ secrets.LIQUIBASE_DEV_DB }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Liquibase Status
        id: liquibase-status
        uses: liquibase-github-actions/checks-run@v4.29.2
        with:
          changelogFile: ${{ env.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
          url: ${{ secrets.LIQUIBASE_DEV_URL }}
          username: ${{ secrets.LIQUIBASE_DEV_USER }}
          password: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}
          licenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
          headless: true
          logLevel: INFO