name: Liquibase Generate Changelog with GitHub Actions Demo
on: 
  workflow_dispatch
jobs:
  liquibase-actions:
    name: Liquibase Actions
    runs-on: ubuntu-latest
    env: 
      RUN: ${{ github.run_number }}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: liquibase/changelogs/generatedChangelog.sql
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate Liquibase changelog file
        id: liquibase-status
        uses: liquibase-github-actions/generate-changelog@v4.29.2
        with:
          url: "jdbc:h2:mem:liquibase_dev"
          changelogFile: ${{ env.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
          headless: true
          logLevel: INFO
      - name: Create Pull Request for updated files
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            add liquibase generated changelog
          title: Add Liquibase Generated Changelog
          token: ${{ secrets.GITHUB_TOKEN }}