name: Liquibase with GitHub Actions Demo
on: [push]
jobs:
  liquibase-update:
    name: Liquibase Update
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_USER: liquibase_user
          POSTGRES_PASSWORD: liquibase_password
          POSTGRES_DB: liquibase_db
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Liquibase Status
        uses: liquibase-github-actions/status@v4.29.2
        with:
          changelogFile: "liquibase/changelog.sql"
          url: "jdbc:postgresql://postgres:5432/liquibase_db"
          username: liquibase_user
          password: liquibase_password
          licenseKey: ${{ secrets.LB_PRO_LICENSE_KEY }}
          headless: true
          logLevel: INFO