name: Liquibase with GitHub Actions Demo
on: [push]
jobs:
  liquibase-status:
    name: Liquibase Status
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: liquibase-github-actions/status@v4.29.2
        with:
          changelogFile: "liquibase/example-changelog.sql"
          defaultsFile: "liquibase/liquibase.properties"
          password: ${{ secrets.DB_PASSWORD_PROD }}
          username: ${{ secrets.DB_USERNAME_PROD }}
          headless: true
          logLevel: INFO