name: Liquibase Flow with GitHub Actions Demo
on: 
  workflow_dispatch
jobs:
  liquibase-actions:
    name: Liquibase Actions
    runs-on: ubuntu-latest
    env: 
        LB_TAG: ${{ github.run_number }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Liquibase Flow File
        id: liquibase-status
        uses: liquibase-github-actions/flow@v4.29.2
        with:
          flowFile: "liquibase/liquibase.flowfile.yaml"
          changelogFile: ${{ env.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
          url: ${{ secrets.LIQUIBASE_DEV_URL }}
          username: ${{ secrets.LIQUIBASE_DEV_USER }}
          password: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}
          licenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
          headless: true
          logLevel: INFO
          labelFilter: "person"