name: Liquibase Flow with GitHub Actions Demo
on: 
  workflow_dispatch
jobs:
  liquibase-actions:
    name: Liquibase Actions
    runs-on: ubuntu-latest
    env: 
        LIQUIBASE_COMMAND_CHANGELOG_FILE: liquibase/changelog.sql
        LIQUIBASE_COMMAND_TAG: ${{ github.run_number }}
        LB_SNAPSHOTS_DIR: "liquibase/snapshots"
        LB_ENVIRONMENT: "DEV"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Liquibase Flow File
        id: liquibase-status
        uses: liquibase-github-actions/flow@v4.29.2
        with:
          url: "jdbc:h2:mem:liquibase_dev"
          changelogFile: ${{ env.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
          flowFile: "liquibase/liquibase.flowfile.yaml"
          licenseKey: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
          headless: true
          logLevel: INFO