name: Liquibase Update and Snapshot with GitHub Actions Demo
on: 
  workflow_dispatch
jobs:
  liquibase-actions:
    name: Liquibase Actions
    runs-on: ubuntu-latest
    env: 
      RUN: ${{ github.run_number }}
      VERSION: "1.0"
      LIQUIBASE_COMMAND_CHANGELOG_FILE: liquibase/changelogs/generatedChangelog.sql
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{ secrets.LIQUIBASE_DEV_USER }}
          POSTGRES_PASSWORD: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}
          POSTGRES_DB: ${{ secrets.LIQUIBASE_DEV_DB }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Liquibase update-sql
        id: liquibase-updatesql
        uses: liquibase-github-actions/update-sql@v4.29.2
        with:
          changelogFile: ${{ env.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
          url: ${{ secrets.LIQUIBASE_DEV_URL }}
          username: ${{ secrets.LIQUIBASE_DEV_USER }}
          password: ${{ secrets.LIQUIBASE_DEV_PASSWORD }} 
          headless: true
          logLevel: INFO
      - name: Run Liquibase Tag
        id: liquibase-tag
        uses: liquibase-github-actions/tag@v4.29.2
        with:
          tag: ${{ env.VERSION }}
          url: ${{ secrets.LIQUIBASE_DEV_URL }}
          username: ${{ secrets.LIQUIBASE_DEV_USER }}
          password: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}    
          headless: true
          logLevel: INFO
      - name: Run Liquibase update
        id: liquibase-update
        uses: liquibase-github-actions/update@v4.29.2
        with:
          changelogFile: ${{ env.LIQUIBASE_COMMAND_CHANGELOG_FILE }}
          url: ${{ secrets.LIQUIBASE_DEV_URL }}
          username: ${{ secrets.LIQUIBASE_DEV_USER }}
          password: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}      
          headless: true
          logLevel: INFO
      - name: Run Liquibase update
        id: liquibase-snapshot
        uses: liquibase-github-actions/snapshot@v4.29.2
        with:
          url: ${{ secrets.LIQUIBASE_DEV_URL }}
          username: ${{ secrets.LIQUIBASE_DEV_USER }}
          password: ${{ secrets.LIQUIBASE_DEV_PASSWORD }}
          snapshotFormat: "JSON"      
          headless: true
          logLevel: INFO
      - name: Create Pull Request for updated files
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            add liquibase snapshot file for ${{ secrets.LIQUIBASE_DEV_DB }}
          title: Add Liquibase Snapshot
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: liquibase-snapshot-${{ env.RUN }}