name: Liquibase Generate Changelog with GitHub Actions Demo
on: 
  workflow_dispatch
jobs:
  liquibase-actions:
    name: Liquibase Actions
    runs-on: ubuntu-latest
    env: 
      RUN: ${{ github.run_number }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate Liquibase changelog file
        id: liquibase-status
        uses: liquibase-github-actions/generate-changelog@v4.29.2
        with:
          url: "jdbc:h2:mem:liquibase_dev"
          changelogFile: "./liquibase/changelogs/generatedChangelog_${{ env.RUN }}.sql}"
          headless: true
          logLevel: INFO