name: Liquibase with GitHub-hosted Docker Demo

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  liquibase-docker-update:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    
    - name: Run 'Liquibase status' in a Docker Container	    
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=./changelogs/changelog.h2.sql --username=admin --password=password status --verbose
    
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=./changelogs/changelåog.h2.sql --username=admin --password=password --logLevel=debug update